import type { Metadata } from "next";
import "@/app/globals.css";
import AnimatedNavBar from "@/components/ui/AnimatedNavBar";
import Image from "next/image";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div
      id="bg_color_container"
      className="w-full relative min-h-screen overflow-auto duration-500"
      style={{
        backgroundImage:
          "url('/img/blue-abstract-waves-3840x2160-17108-gray.jpeg')",
        backgroundSize: "cover",
        backgroundPosition: "center",
        backgroundAttachment: "fixed", // Optional for a fixed background effect
        backgroundBlendMode: "overlay", // Adds mix-blend-overlay effect

        backgroundColor: "#6b21a8", // Adds a background color for blending
      }}
    >
      <div className="relative z-10 h-full max-w-6xl mx-auto flex w-full items-center transition-colors">
        <div className="w-full mx-auto">
          <AnimatedNavBar />
          <div className="mx-10 mt-7">{children}</div>
        </div>
      </div>
    </div>
  );
}
