import type { Metadata } from "next";
import localFont from "next/font/local";
import "@/app/globals.css";
import AnimatedNavBar from "@/components/ui/AnimatedNavBar";

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div
          id="bg_color_container"
          className="w-full min-h-screen overflow-auto duration-500"
        >
          <div className="h-full max-w-6xl mx-auto flex w-full items-center  transition-colors">
            <div className="w-full mx-auto">
              <AnimatedNavBar />
              <div className="mx-5 mt-3">{children}</div>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
